### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by vaniron** [spyproof/PixelmonTechnicFix#1]
Hello,
can you give me some contact of yours? Email, skype, facebook?

**Comment by TPNils** [comment]
If you have any questions or issues, feel free to post them here on this thread or explain why you need these persenal details.

**Comment by vaniron** [comment]
Well i would like to offer some bussiness staff, basicaly some customization for my own modpack, which you can possibly make for me for some money.

If you are interested, contact me at dvotom@pixelmon.cz

**Comment by TPNils** [comment]
you can contact me on jan.halt64@gmail.com
