### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by LazerCorn3114** [spyproof/PixelmonTechnicFix#2]
Pixelmon has patched this is it possible for you to make a new fix? It seem like there fixes are located here `com.pixelmonmod.pixelmon.util.helpers.RequirementsChecker`.

**Comment by Hiroku** [comment]
How about you stop actively trying to hurt Pixelmon, the very hand that's feeding you?

**Comment by TPNils** [comment]
@LazerCorn3114 I will be posting a new update later today. Thank you for notifing me about this.

**Comment by TPNils** [comment]
Updated the fix
